image: freebsd/12.x
packages:
  - ruby
  - rubygem-gems
  - rubygem-rake
  - zeromq
  - czmq
sources:
  - hg+https://hg.sr.ht/~ged/Strelka
tasks:
  - setup: |
      cd Strelka
      gem install --user-install -Ng
  - test: |
      export PATH=$PATH:$(ruby -r rubygems -e 'puts Gem.user_dir')/bin
      cd Strelka
      COVERAGE=1 rspec -cfd
