# -*- ruby -*-

# DO NOT EDIT THIS FILE. Instead, edit Rakefile, and run `rake bundler:gemfile`.

source "https://rubygems.org/"

gem "configurability", "~>2.1"
gem "foreman", "~>0.62"
gem "highline", "~>1.6"
gem "inversion", "~>0.12"
gem "loggability", "~>0.9"
gem "mongrel2", "~>0.41"
gem "pluggability", "~>0.4"
gem "sysexits", "~>1.1"
gem "trollop", "~>2.0"
gem "uuidtools", "~>2.1"
gem "safe_yaml", "~>1.0"

gem "hoe-mercurial", "~>1.4", :group => [:development, :test]
gem "hoe-deveiate", "~>0.6", :group => [:development, :test]
gem "hoe-highline", "~>0.2", :group => [:development, :test]
gem "rdoc", "~>4.0", :group => [:development, :test]
gem "hoe-bundler", "~>1.2", :group => [:development, :test]
gem "rspec", "~>3.0", :group => [:development, :test]
gem "simplecov", "~>0.7", :group => [:development, :test]
gem "rdoc-generator-fivefish", "~>0.2", :group => [:development, :test]
gem "hoe", "~>3.12", :group => [:development, :test]

# vim: syntax=ruby
