#!/usr/bin/env ruby
#encoding: utf-8

require 'strelka'


# The main <%= project %> application
class <%= klass %>::Application < Strelka::App

	# Uncomment this if you need an appid other than 
	# '<%= klass.gsub(/[^[:alnum:]]+/, '-').downcase %>-application'.
	#ID = '<%= XIF %>' # (set the app id of the main application)

	# Load some plugins
	plugins :templating, :routing

	# By default, responses are HTML
	default_type 'text/html'

	# Templating -- wrap everything in the layout
	layout 'layout.tmpl'
	templates \
		:top => 'top.tmpl'


	# GET request handler -- handles all GET requests
	get do |req|
		# Use the 'top' template for the body, wrapped in the 'layout' template
		return :top
	end


end # class <%= klass %>::Application


<%= klass %>::Application.run if __FILE__ == $0

