#!/usr/bin/env ruby

require 'inversion'
require 'strelka'

# The Strelka setup web application.
class Strelka::SetupProcess < Strelka::App

	# NOTE:
	# This is currently just a sketch for an idea of how Strelka could support stateful
	# 'process' applications ala Tir's coroutine-based "natural" handlers. It's not
	# implemented yet, so this will error:
	plugins :process

	layout 'setup/layout.tmpl'

	views :step1 => 'setup/step1',
	      :step2 => 'setup/step2'


	### Progress through the setup process.
	def main( req )
		params = show( :step1 )
		params = show( :step2, params )

	end

end # class Strelka::AdminConsole


Strelka::SetupProcess.run( 'strelka-setup' )

