# Foreman procfile
mongrel: m2sh.rb -c mongrel2.sqlite start
helloworld: ../bin/strelka -D . -l warn -c config.yml start hello-world
auth: ../bin/strelka -D . -l warn -c config.yml start auth-demo
auth2: ../bin/strelka -D . -l warn -c config.yml start auth-demo2
sessions: ../bin/strelka -D . -l debug -c config.yml start sessions-demo
# ws: ../bin/strelka -l info -c config.yml start ws-echo

