#!/usr/bin/env ruby

require 'strelka'

# The Strelka admin web console.
class HelloWorldApp < Strelka::App

	# The route appid that will configure this app if no appid is specified
	ID = 'hello-world'


	# Use Sinatra-like routing
	plugins :routing

	# Set responses to plaintext if they don't specify differently
	default_type 'text/plain'

	# Handle all GET requests the same way
	get do |req|
		res = req.response
		res.puts 'Hello, world!'
		return res
	end

end # class HelloWorldApp


# Run the app
Encoding.default_internal = Encoding::UTF_8
HelloWorldApp.run if __FILE__ == $0
